// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzycEQ_dybYilCfSlnpjuj_6Z5fCrPgQ',
    appId: '1:463185682464:web:ec9a626987cdcc45151c45',
    messagingSenderId: '463185682464',
    projectId: 'fir-demo-e121e',
    authDomain: 'fir-demo-e121e.firebaseapp.com',
    storageBucket: 'fir-demo-e121e.appspot.com',
    measurementId: 'G-5W9VFJJ6PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASabsNnaNIQSS35CJ_70Tzuw5R3pvDL-w',
    appId: '1:463185682464:android:31223f85ba343fe5151c45',
    messagingSenderId: '463185682464',
    projectId: 'fir-demo-e121e',
    storageBucket: 'fir-demo-e121e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1uPkt4iUGlUZRQApycHrP_Tv-QtLcnj8',
    appId: '1:463185682464:ios:69e7c6038145d077151c45',
    messagingSenderId: '463185682464',
    projectId: 'fir-demo-e121e',
    storageBucket: 'fir-demo-e121e.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1uPkt4iUGlUZRQApycHrP_Tv-QtLcnj8',
    appId: '1:463185682464:ios:69e7c6038145d077151c45',
    messagingSenderId: '463185682464',
    projectId: 'fir-demo-e121e',
    storageBucket: 'fir-demo-e121e.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZzycEQ_dybYilCfSlnpjuj_6Z5fCrPgQ',
    appId: '1:463185682464:web:1acd5cc34cfd5dd5151c45',
    messagingSenderId: '463185682464',
    projectId: 'fir-demo-e121e',
    authDomain: 'fir-demo-e121e.firebaseapp.com',
    storageBucket: 'fir-demo-e121e.appspot.com',
    measurementId: 'G-Q98M8ZG6GK',
  );

}